### ISSUE TITLE
Allow "+" timezone-part

### ISSUE THREAD

**Issue by mj1856** [ryzokuken/draft-ryzokuken-datetime-extended#10]
By the current definition, IANA zones like `Etc/GMT+1` would not be allowed.  `timezone-part` needs to allow a `+` character.

**Comment by ryzokuken** [comment]
so this only includes timezones `"Etc/GMT" +/- 2DIGIT`, right?

The rest don't have + or -, right? I'll add a special case for these.

**Comment by mj1856** [comment]
There is one valid old-style link named `GMT+0`, so I suggest that `+` be a valid character anywhere in the `time-zone-part` rather than special casing it.

**Comment by ryzokuken** [comment]
is it necessary for us to support that old-style link? I just want to avoid the RFC grammar having to accommodate `+` anywhere in the time-zone name for a long time just because of an old improperly named timezone especially since there's no backwards compatibility to take care of right now.

**Comment by mj1856** [comment]
Unfortunately, I believe it is still necessary to support it.  It's a valid tz identifier, same as all of the other links in the `backward` file.

https://github.com/eggert/tz/blob/2020f/backward#L87

The `backward` file is included in almost every distribution by default  (unlike the `backzone` file which is not).

**Comment by mj1856** [comment]
FWIW, There aren't any zones or links that have `.` in their name - despite the guidance in the theory file.

**Comment by ryzokuken** [comment]
@mj1856 I understand. I'll update the grammar.

**Comment by ryzokuken** [comment]
please take a look now!
