### ISSUE TITLE
Should we allow UTS 35 style timezone IDs?

### ISSUE THREAD

**Issue by sffc** [ryzokuken/draft-ryzokuken-datetime-extended#14]
IANA is the main arbitrator of timezone IDs.  However, Unicode also publishes a competing set of timezone IDs that are shorter and designed to fit into locale subtags.

https://github.com/unicode-org/cldr/blob/master/common/bcp47/timezone.xml

For example, maybe we should support suffixes such as `[u-tz-uschi]` as an alternative to `[America/Chicago]`.  Advantages:

1. Increased compatibility with BCP 47
2. The Unicode IDs can be substantially shorter; for example, `[u-tz-usind]` instead of `[America/Indiana/Indianapolis]`

CC @macchiati @yumaoka

**Comment by ryzokuken** [comment]
I suppose we can avoid standardizing calendars and timezones in the RFC at all, instead just adding the suffix pattern and standardize both those tags in Unicode-land?

A middle ground could be to keep the current timezone format (esp useful for Java compat) but also standardize `u-tz` in Unicode so we can allow the use of either?

**Comment by sffc** [comment]
I think the RFC should *allow* either the Java-style of the UTS 35-style time zone IDs to be used, and implementations can decide whether to support one, both, or neither.

**Comment by sffc** [comment]
CC @justingrant

**Comment by justingrant** [comment]
Until reading this GH issue, I had no idea that this alternate format existed. But the IANA format seems to be widely used: Java, Linux, etc. I'd suggest we stick with the more popular format.

**Comment by sffc** [comment]
> I'd suggest we stick with the more popular format.

In addition to the UTS 35 format as an option for implementers, or instead of it?

**Comment by ryzokuken** [comment]
I suppose we can special case IANA tzs for backwards compatibility with the non-standardized Java format (I could perhaps add a paragraph with the backing rationale). The Unicode spec could define its own `u-tz-` field for future implementations.

**Comment by ryzokuken** [comment]
@sffc now that #13 has landed, I think it can (and probably should be) be done, but it would have to be done in the corresponding Unicode spec. On that note, how can we get the ball rolling in Unicode?

**Comment by sffc** [comment]
The Unicode time zone identifiers have some technical advantages over the IANA ones, explained [here](https://unicode.org/reports/tr35/tr35-dates.html#Time_Zone_Names).

> On that note, how can we get the ball rolling in Unicode?

It would be nice if we can do the same process as BCP47.  See http://cldr.unicode.org/index/bcp47-extension.  We might want to add a section 3.12 [here](https://www.unicode.org/reports/tr35/tr35.html#Contents), similar to sections 3.6 and 3.7.  I don't know if we'll need an additional RFC like [6067](https://tools.ietf.org/html/rfc6067).

**Comment by ryzokuken** [comment]
I suppose it is safe to close this. The answer is yes, we should support them, but it does not need to be done in this draft.
