### ISSUE TITLE
To what extend should suffix items be ordered?

### ISSUE THREAD

**Issue by gibson042** [ryzokuken/draft-ryzokuken-datetime-extended#15]
The current text specifies
```
suffix         = [time-zone] [calendar] *suffix-part
```
This prohibits calendar before time zone and generic suffix before calendar. Is that intentional?

**Comment by ryzokuken** [comment]
According to #13, the calendar is no longer special-cased and should be treated like any other suffix part. That should fix this issue.

**Comment by ryzokuken** [comment]
The current state is that timezone comes first and everything else comes after that. Is that acceptable?

**Comment by sffc** [comment]
I think the suffixes should be accepted in any order.  I think the question is, what happens when suffixes conflict?  Like, say you have `[u-ca-hebrew][u-ca-japanese]`.  What do you do?  I think you should pick either the first or the last to "win".  I vote for the first.

This also would generalize for #14; if you had `[America/New_York][u-tz-uschi]`, then the first suffix would win.

**Comment by sffc** [comment]
How does suffix ordering work with private use?  If you had `[x-foo-bar][x-foo-baz]`, how should you interpret that?

**Comment by ryzokuken** [comment]
The suffix are accepted in any order, except for the special-cased IANA tz none which occurs either at the beginning of the suffix or not at all. I had done this keeping compatibility in mind as implementations can just quickly update to ignore the rest of the suffix for the time-being.

**Comment by ryzokuken** [comment]
Oh, on that note, I will add a sentence for giving precedence to the first occurrence of any key in the draft.

> How does suffix ordering work with private use? If you had [x-foo-bar][x-foo-baz], how should you interpret that?

According to the rule discussed above, it would be the same as `[x-foo-bar]`. Since the namespace and the key is the same, the first value is given precedence.
