### ISSUE TITLE
Should generic suffixes allow arbitrary values?

### ISSUE THREAD

**Issue by gibson042** [ryzokuken/draft-ryzokuken-datetime-extended#16]
The current text specifies
```
suffix-part    = "[" 1*ALPHA "=" 1*VCHAR "]"
```
This is certainly too broad, because [VCHAR](https://tools.ietf.org/html/rfc5234#appendix-B.1) includes `[` and `]`, creating a parsing hazard. It also allows `\`, `"`, and `'` with no special semantics, and prohibits U+0020 SPACE. Do we want to think about quoting/escaping mechanisms, or at least leaving the door open for them?

Also, do we want to allow "bare" extensions that specify a key with no value, e.g. `[x-private]`?

**Comment by ryzokuken** [comment]
I don't know if there's any valid reason to use a space in a value, but I'd be happy to restrict values to be hyphen separated alphanumeric strings. What do you think?

**Comment by ryzokuken** [comment]
> Also, do we want to allow "bare" extensions that specify a key with no value, e.g. [x-private]?

keyless namespaces are allowed now eg: `[namespace-value]`.

For the rest, Mark Davis also suggested limiting to alphanum instead of `VCHAR` so I'd go ahead and make that restriction.

**Comment by ryzokuken** [comment]
@gibson042 can you approve this so we can make a new revision?

**Comment by ryzokuken** [comment]
I merged it, please feel free to let me know if something is amiss.

**Comment by gibson042** [comment]
`alphanum` may be a little too restrictive; we already know that some calendar names are hyphenated (e.g., islamic-umalqura).
