### ISSUE TITLE
How to distinguish between time zone and other suffixes?

### ISSUE THREAD

**Issue by sffc** [ryzokuken/draft-ryzokuken-datetime-extended#22]
In #9 @ptomato said:

> Note that BCP 47 pairs, if the value consists of only one segment with no digits (e.g.: `u-ca-gregory`), are legal (though unlikely) IANA time zone identifiers:
> 
> > Use only valid POSIX file name components (i.e., the parts of names other than `/`). Do not use the file name components `.` and `..`. Within a file name component, use only ASCII letters, `.`, `-` and `_`. Do not use digits, as that might create an ambiguity with POSIX TZ strings. A file name component must not exceed 14 characters or start with `-`.
> 
> This is awkward for parsers, because the IANA time zone suffix may be omitted. I think this should be reopened and the tag format change reconsidered.

Basically, what we need is a way to determine whether the suffix is an IANA time zone or a BCP-47-like extension.  A few possible ways we can do this:

1. Require IANA time zones to contain a `/`?
2. Require IANA time zones to start with a capital letter?
3. Add back a `=` in other suffixes like `[u-ca=...]` instead of `[u-ca-...]`

**Comment by ptomato** [comment]
Option 1 would disallow `[UTC]`. I think Option 2 would fit all existing IANA time zones but would preclude implementations from treating strings case-insensitively, which seems like a common thing they might want to do.

**Comment by ryzokuken** [comment]
I suppose opt. 1 is not valid as @ptomato pointed out. I don't feel strongly about ruling out option 2. Do we know any implementations that support the extended format and allow case insensitive IANA tz names?

**Comment by ptomato** [comment]
ECMA-402 treats time zone names [case insensitively](https://tc39.es/ecma402/#sec-canonicalizetimezonename), so it would be odd if the date-time format didn't.

**Comment by ryzokuken** [comment]
Ugh, you're right. @sffc can you ask Mark if the `=` instead of hyphen would be too inconvenient?

**Comment by sffc** [comment]
@macchiati For datetime strings, is a suffix `[u-ca=hebrew]` acceptable instead of `[u-ca-hebrew]`?

**Comment by macchiati** [comment]
I think either works: there is a direct (very simple) transform between
them, so it is easy to map the = form to the corresponding BCP47 suffix.

Mark
