### ISSUE TITLE
Support UTC offsets with non-integral minutes and seconds

### ISSUE THREAD

**Issue by ptomato** [ryzokuken/draft-ryzokuken-datetime-extended#4]
Historical time zones may have offsets from UTC that are not a whole number of minutes. In §4.2 we currently say that offsets must be in whole minutes, but we could say that seconds (including digits after a decimal separator) are allowed in a numeric offset.

**Comment by ryzokuken** [comment]
Done in https://github.com/ryzokuken/draft-ryzokuken-datetime-extended/commit/11f299bc8f8479149ff7e15a8ea0e059c16b885b.
