### ISSUE TITLE
Support extended 6-digit years

### ISSUE THREAD

**Issue by ptomato** [ryzokuken/draft-ryzokuken-datetime-extended#6]
ISO 8601 allows an "extended year" format of an agreed-upon number of digits if preceded by a `+` or `-` sign character. JavaScript has popularized this due to supporting 6-digit extended years. This could be considered for inclusion as well.

**Comment by ryzokuken** [comment]
Done in https://github.com/ryzokuken/draft-ryzokuken-datetime-extended/commit/11f299bc8f8479149ff7e15a8ea0e059c16b885b.
