### ISSUE TITLE
What is the "generalized format"?

### ISSUE THREAD

**Issue by sffc** [ryzokuken/draft-ryzokuken-datetime-extended#8]
In your draft, Figure 10 says

>
> ```
> 1937-01-01T12:00:27.87+00:19:32.130[foo=bar][baz=bat]
> ```
>
> This timestamp utilizes the generalized format to declare two additional pieces of information in the suffix that can be interpreted by any compatible implementations and ignored otherwise.

Where is the generalized format specified?  I guess it is the "suffix-part" from here?

```
suffix-part    = "[" 1*ALPHA "=" 1*VCHAR "]"
```

**Comment by ryzokuken** [comment]
Yes! Is that text too confusing? I could modify it to better explain things...

**Comment by ryzokuken** [comment]
Hi @sffc! What changes would be appropriate here?

**Comment by sffc** [comment]
I think you should just replace the word "generalized" with "private use".

**Comment by ryzokuken** [comment]
Sure.
