### ISSUE TITLE
Use namespaced key/value pairs

### ISSUE THREAD

**Issue by sffc** [ryzokuken/draft-ryzokuken-datetime-extended#9]
Instead of `[c=...]` and `[foo=...]`, I think it should be `[u-ca-...]` and `[x-foo-...]`.  Unicode defines what follows `u-`.

There is precedent for this. See [BCP 47 Section 2.6.6](https://tools.ietf.org/html/bcp47#section-2.2.6).

**Comment by sffc** [comment]
CC @macchiati

**Comment by ryzokuken** [comment]
I'd be happy to do that if @macchiati agrees as well. That said, I'm not quite sure about a few facts:

1. Would a single character suffice for a namespace? Are we sure we will never need a 27th namespace?
2. Would we need a way to decide which namespaces belong to which standards body/organization?

Also we need to probably add a paragraph of rationale about it above the grammar.

**Comment by macchiati** [comment]
Good questions. 

First, I agree with Shane's proposal. It scopes the key-value pairs, and makes a clear mapping.

As for #1, I think what you could do is define define the first subtag as the top level of the namespace, where:

- All single letters are allocated to matching BCP47 extensions (or private use). (So that is currently u, t, x)
- Other first first subtags are reserved for future expansion (and you can decide any process for allocation later on)

**Comment by ryzokuken** [comment]
I will update the grammar accordingly, but let's use this issue to work through what the paragraph about it says?

**Comment by sffc** [comment]
IMO, the spec should list the legal namespaces.  We start by reserving two namespaces: `u-` and `x-`.  If someone else comes along in a year and wants another namespace, then they can publish yet another new version of this RFC, or hopefully by that time CalConnect.

In the unlikely situation where we run out of single-letter namespaces, then future spec authors can use two-letter namespaces.  They will be backwards compatible so long as we require a separator after the namespace.  For example, `foo-` could be a namespace in the future.

**Comment by sffc** [comment]
Now, an interesting question is whether the RFC should say specifically *what* is allowed to appear inside Unicode's namespace.  Should the RFC say that there is a calendar identifier?  Or does it say simply that everything after `u-` is up to Unicode to decide, and then we publish a small Unicode spec with the details?

**Comment by ryzokuken** [comment]
I'd prefer a Unicode spec that specifically talks about the different tags supported/maintained by Unicode so we don't end up centralizing adding/removing stuff to an existing namespace to the RFC.

One interesting side-effect is, do we even need to discuss the calendar stuff in the RFC anymore?

**Comment by sffc** [comment]
In the RFC we could specify syntax such as the following (in regex syntax):

```
\[(u|x)-[a-z0-9]+(-[a-z0-9]+)\]
```

Questions:

1. Do we want to impose subtag component lengths like in BCP 47, or just allow subtags of any length?  i.e., is something like `[x-abcdefghijklmnop]` legal in the RFC, or do we require it to be broken up?  Note that we don't really need the restriction as in BCP 47, because if we want multiple extensions, we put them in the string like this: `[u-ext1][u-ext2][x-ext3]` rather than in BCP47 where they need to be concatenated together like `-u-ext1-u-ext2-x-ext3`
2. Are there any other characters we should allow inside the brackets?  Or is alphanum + `-` sufficient?  Maybe it's good to restrict the characters to make the string easier to process.

**Comment by sffc** [comment]
> One interesting side-effect is, do we even need to discuss the calendar stuff in the RFC anymore?

Well, that's an interesting question.  On the one hand, I think it is useful for the RFC to discuss the motivation and that the main reason for having this syntax is to support non-ISO calendar systems.  On the other, Unicode should of course be in charge of specifying exactly which calendar systems.

I'm mainly wondering whether we should make the spec be: "`u-` followed by something spec'd by Unicode" or "`u-ca-` followed by something spec'd by Unicode".  For that matter, it might be okay to do "`c-` followed by something spec'd by Unicode".

**Comment by ryzokuken** [comment]
> Do we want to impose subtag component lengths like in BCP 47, or just allow subtags of any length? i.e., is something like [x-abcdefghijklmnop] legal in the RFC, or do we require it to be broken up? Note that we don't really need the restriction as in BCP 47, because if we want multiple extensions, we put them in the string like this: [u-ext1][u-ext2][x-ext3] rather than in BCP47 where they need to be concatenated together like -u-ext1-u-ext2-x-ext3

As you rightly pointed out, I don't think it's really necessary in this case.

> Are there any other characters we should allow inside the brackets? Or is alphanum + - sufficient? Maybe it's good to restrict the characters to make the string easier to process.

for now the key can contain only alphabets and the value can contain any visible ASCII character.

**Comment by ryzokuken** [comment]
I added a WIP paragraph explaining the namespaces rationale to the spec in the PR, please check it out. Feedback appreciated.

**Comment by macchiati** [comment]
I think it would be cleaner to just reserve all the single-ASCII letters
for BCP47 extensions and private use, and reference BCP47 for their
specifications. It can also reference Unicode directly for t and u. You
could then indicate which of them are required/allowed in your spec. For
example, if you are excluding all t-... then you can say so there.

Mark

**Comment by ryzokuken** [comment]
>  On the one hand, I think it is useful for the RFC to discuss the motivation and that the main reason for having this syntax is to support non-ISO calendar systems. On the other, Unicode should of course be in charge of specifying exactly which calendar systems.

I think we'd reference Unicode for the actual set of supported calendars either way, but I think it's fine to talk in general terms: the motivation is to allow specifying additional information, and the calendar is just one of the many options in the Unicode namespace (in an arbitrary future atleast).

**Comment by ryzokuken** [comment]
> I'm mainly wondering whether we should make the spec be: "u- followed by something spec'd by Unicode" or "u-ca- followed by something spec'd by Unicode".

The latter is what we have right now, the former is what I was thinking about...

> For that matter, it might be okay to do "c- followed by something spec'd by Unicode".

Do you see any upsides for this (especially special casing calendars) as opposed to just `u-ca-`?

**Comment by sffc** [comment]
The difference I see between date identifiers and locale identifiers is that the calendar system is much more strongly tied to a date than it is to a locale.  In a date, the calendar system has a significant effect on how the date should be interpreted.  In a locale, it's a user preference, but it is supplemental information that doesn't change the language.

From this perspective, I can see an argument for specing the calendar key directly in the RFC, either `u-ca-` or `c-`.

**Comment by ryzokuken** [comment]
> The difference I see between date identifiers and locale identifiers is that the calendar system is much more strongly tied to a date than it is to a locale. In a date, the calendar system has a significant effect on how the date should be interpreted. In a locale, it's a user preference, but it is supplemental information that doesn't change the language.

I agree. That said, I feel that keeping the calendar a first-class information type (as `u-ca-`) while leaving `u-*` to a Unicode spec is a bit confusing so if we choose to identify the calendar as such, we should probably reserve a special `c-` prefix for it. What do you think?

**Comment by ryzokuken** [comment]
(of course, the benefit of *not* doing that would be the possibility of a pretty looking `[u-tz-foo][u-ca-bar]` suffix)

**Comment by sffc** [comment]
I'm okay with `c-` for calendars and `x-` for private use, but like you just said, there's a nice parallel with `u-ca` and `u-tz`.  Maybe `ca-`, `tz-`, and `x-`?

**Comment by ryzokuken** [comment]
You mean `tz-` in the place of `u-tz-`? Does that mean we'd special case both IANA tz and `tz-`?

**Comment by sffc** [comment]
`[IANA]` and `[tz-bcp47]` would both be listed in the RFC as options for implementers.

**Comment by ptomato** [comment]
Note that BCP 47 pairs, if the value consists of only one segment with no digits (e.g.: `u-ca-gregory`), are legal (though unlikely) IANA time zone identifiers:

> Use only valid POSIX file name components (i.e., the parts of names other than `/`). Do not use the file name components `.` and `..`. Within a file name component, use only ASCII letters, `.`, `-` and `_`. Do not use digits, as that might create an ambiguity with POSIX TZ strings. A file name component must not exceed 14 characters or start with `-`.

This is awkward for parsers, because the IANA time zone suffix may be omitted. I think this should be reopened and the tag format change reconsidered.

**Comment by sffc** [comment]
#22
